# Generated by Django 4.2.8 on 2024-05-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieboardcomment',
            old_name='userId',
            new_name='user',
        ),
    ]
