# Generated by Django 4.2.8 on 2024-05-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeboardarticle',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='freeboardcomment',
            old_name='userId',
            new_name='user',
        ),
    ]
