# Generated by Django 4.2.8 on 2024-05-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(),
        ),
    ]
