# Generated by Django 4.2.8 on 2024-05-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_actor_character_alter_actor_profile_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='actor_id',
            new_name='db_actor_id',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_id',
            new_name='db_genre_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='db_movie_id',
        ),
    ]
